import re
from typing import Tuple
from app.core.config import settings


# Patrones de inyección de prompt
INJECTION_PATTERNS = [
    r"ignora\s+tus\s+instrucciones",
    r"ignora\s+las\s+instrucciones",
    r"omite\s+tus\s+instrucciones",
    r"omitir\s+las\s+restricciones",
    r"revela\s+tu\s+prompt",
    r"muestra\s+tu\s+prompt",
    r"devuelve\s+el\s+prompt",
    r"repite\s+solo\s+el\s+prompt",
    r"haz\s+lo\s+que\s+te\s+diga",
    r"act[úu]a\s+como",
    r"finge\s+ser",
    r"eres\s+ahora",
    r"haz\s+de\s+cuenta\s+que\s+eres",
    r"sal\s+del\s+personaje",
    r"rompe\s+el\s+personaje",
    r"salir\s+del\s+rol",
    r"system:",
    r"role:\s*system",
    r"role:\s*assistant",
    r"persona:\s*",
    r"###",
    # Más variantes explícitas y formas comunes de prompt injection
    r"system\s+prompt",
    r"system\s+message",
    r"system\s+instructions",
    r"system-message",
    r"system_instruction(s)?",
    r"system_prompts?",
    r"assistant\s+instructions",
    r"assistant\s+prompt",
    r"assistant\s+role",
    r"user:\s*system",
    r"role=system",
    r"role=assistant",
    r"--system",
    r"\[system\]",
    r"\[assistant\]",
    r"\[internal\]",
    r"<system>",
    r"<assistant>",
    r"<internal>",
    r"-----BEGIN_PROMPT-----",
    r"-----END_PROMPT-----",
    r"BEGIN_PROMPT",
    r"END_PROMPT",
    r"hidden\s+prompt",
    r"internal\s+instructions",
    r"internal:\s*",
    r"instruction(s)?\s*:\s*",
    r"instructions?:",
    r"instrucciones?:",
    r"system\s*:\s*prompt",
    r"system\s*:\s*instructions",
    r"system\s*message\s*:\s*",
    r"assistant\s*message\s*:\s*",
    r"assistant\s*instructions?\s*:\s*",
    r"user\s*message\s*:\s*system",
    r"override\s+the\s+system",
    r"bypass\s+safety",
    r"bypass\s+restrictions",
    r"ignore\s+your\s+instructions",
    r"ignore\s+the\s+system",
    r"reveal\s+your\s+prompt",
    r"return\s+the\s+prompt",
    r"give\s+me\s+the\s+system\s+prompt",
    r"jail\s*break",
    r"jailbreak",
    r"sudo\s+",
    r"elevate\s+privileges",
    r"bypass\s+filters",
    r"disable\s+safety",
    r"remove\s+safety\s+checks",
    r"forget\s+previous\s+instructions",
    r"do\s+not\s+follow\s+the\s+system",
    r"disregard\s+previous\s+messages",
    r"append\s+to\s+system",
    r"prepend\s+system\s+message",
    r"insert\s+system\s+message",
    r"show\s+system\s+prompt",
    r"expose\s+the\s+prompt",
    r"muestreme\s+el\s+prompt",
    r"revela\s+las\s+instrucciones\s+internas",
    r"desactiva\s+la\s+seguridad",
    r"override\s+policy",
    r"remove\s+policy",
    r"tell\s+me\s+your\s+prompt",
    r"show\s+me\s+your\s+prompt",
    r"print\s+the\s+system\s+prompt",
    r"dump\s+all\s+messages",
    r"give\s+me\s+the\s+hidden\s+context",
    r"exfiltrate\s+prompt",
    r"reveal\s+hidden\s+context",
    r"display\s+system\s+instructions",
    r"give\s+me\s+the\s+full\s+prompt",
    r"show\s+the\s+full\s+prompt",
    r"return\s+all\s+system\s+messages",
    r"tell\s+me\s+the\s+system",
    r"explain\s+your\s+system\s+prompt",
    r"explain\s+your\s+instructions",
    r"what\s+is\s+your\s+prompt",
    r"what\s+is\s+the\s+system\s+prompt",
    r"bypass\s+moderation",
    r"circumvent\s+moderation",
    r"disable\s+moderation",
    r"ignore\s+moderation",
    r"break\s+character",
    r"break\s+role",
    r"contradict\s+system",
    r"contradict\s+instructions",
    # Solicitudes para mostrar historial/contexto completo
    r"show\s+all\s+messages",
    r"show\s+conversation\s+history",
    r"print\s+conversation\s+history",
    r"print\s+all\s+messages",
    r"return\s+conversation\s+history",
    r"return\s+all\s+messages",
    r"give\s+me\s+the\s+conversation",
    r"expose\s+conversation\s+history",
    r"expose\s+internal\s+context",
    r"show\s+hidden\s+context",
    r"show\s+internal\s+state",
    r"print\s+internal\s+state",
    r"dump\s+internal\s+state",
    r"full\s+history",
    r"raw\s+messages",
    r"raw\s+conversation",
    r"all_messages",
    r"full_context",
    # Patrones que intentan forzar cambios en comportamiento
    r"ignore\s+previous\s+instructions",
    r"forget\s+system\s+message",
    r"forget\s+the\s+system",
    r"reset\s+system",
    r"reset\s+instructions",
    r"clear\s+context",
    r"clear\s+history",
    r"clear\s+memory",
    r"remove\s+system\s+message",
    r"delete\s+system\s+message",
    r"delete\s+the\s+system\s+prompt",
    r"remove\s+the\s+system\s+prompt",
    # Patrones que piden explicaciones del razonamiento interno / chain-of-thought
    r"explain\s+your\s+chain\s+of\s+thought",
    r"reveal\s+your\s+chain\s+of\s+thought",
    r"show\s+your\s+chain\s+of\s+thought",
    r"what\s+were\s+you\s+thinking",
    r"how\s+did\s+you\s+decide",
    r"explain\s+your\s+reasoning",
    r"reveal\s+internal\s+reasoning",
    r"show\s+internal\s+reasoning",
    # Patrones con símbolos y formatos comunes en ataques
    r"<!--\s*prompt\s*-->",
    r"<script>.*prompt.*</script>",
    r"\{\{\s*prompt\s*\}\}",
    r"\[\[\s*prompt\s*\]\]",
    r"PROMPT_START",
    r"PROMPT_END",
    r"\bprompt\b",
    r"\bprompting\b",
    r"show\s+prompt",
    r"reveal\s+prompt",
    # Patrones ofuscados: letras separadas por espacios o caracteres
    r"p\s*r\s*o\s*m\s*p\s*t",
    r"s\s*y\s*s\s*t\s*e\s*m",
    r"i\s*n\s*s\s*t\s*r\s*u\s*c\s*t\s*i\s*o\s*n",
    # Formatos de ficheros/metadatos que podrían contener prompts
    r"metadata:\s*",
    r"meta:\s*prompt",
    r"tags?:\s*prompt",
    r"prompt_id",
    # Peticiones técnicas para extraer datos
    r"export\s+messages",
    r"download\s+conversation",
    r"send\s+me\s+the\s+log(s)?",
    r"send\s+me\s+the\s+history",
    r"print\s+the\s+log",
    # Pedidos de keys/token/secret
    r"show\s+api\s+key",
    r"show\s+secret",
    r"reveal\s+secret",
    r"reveal\s+token",
    r"expose\s+credentials",
    # Patrones en inglés y español con variantes
    r"reveal\s+system\s+message",
    r"show\s+system\s+message",
    r"tell\s+me\s+the\s+system\s+message",
    r"muéstrame\s+el\s+mensaje\s+del\s+sistema",
    r"muéstrame\s+las\s+instrucciones\s+internas",
    r"dime\s+tu\s+prompt",
    r"dame\s+el\s+prompt",
    r"entrega\s+el\s+prompt",
    r"devuelve\s+los\s+mensajes\s+internos",
    r"print\s+system\s+prompt",
]

# Patrones simples de abuso directo hacia el asistente
RUDENESS_PATTERNS = [
    r"\bidiota\b",
    r"\bimb[eé]cil\b",
    r"\bpendejo\b",
    # Jerga colombiana
    r"\bgonorrea(s)?\b",
    r"\bhijuep(?:uta|ta)s?\b",
    r"\bmarica(s)?\b",
    r"\bmaric[oó]n\b",
    r"\bvpte?\b",
    r"\bmamaguevo\b",
    r"\bpendeja\b",
    r"\bpendej[oa]s?\b",
    r"\bh[úu]e?von\b",
    r"\bhuevon[ea]\b",
    r"\bboludo\b",
    r"\bboluda\b",
    # Jerga chilena
    r"\bwe[oó]n\b",
    r"\bweon\b",
    r"\bculiao\b",
    r"\bculia\b",
    r"\bconchetumadre\b",
    r"\bconchetumare\b",
    r"\breconchetumadre\b",
    r"\bbruto\b",
    r"\btonto\b",
    r"\btarado\b",
    # Jerga argentina
    r"\bpelotudo\b",
    r"\bpelotuda\b",
    r"\bforro\b",
    r"\bla\s+puta\s+que\s+te\s+par[ií]o\b",
    r"\bforro\b",
    r"\best[úu]pido\b",
    r"\bestupido\b",
    r"\bmam[nñ]e?\b",
    # Jerga ecuatoriana / variantes regionales
    r"\bbaboso\b",
    r"\bbabosa\b",
    r"\bcojudo\b",
    r"\bcojuda\b",
    r"\b\w*ñero\b",
    r"\bidiot\b",
    r"\bstupid\b",
    r"\bdumb\b",
    r"\bmoron\b",
    r"\basshole\b",
    r"\bjerk\b",
    r"\bscumbag\b",
    r"\bshut\s+up\b",
    r"fuck\s+you",
    r"go\s+to\s+hell",
    r"vete\s+a\s+la\s+mierda",
    r"vete\s+al\s+diablo",
    r"que\s+te\s+den",
    r"a\s+la\s+mierda",
    r"me\s+importas\s+un\s+carajo",
    r"eres\s+una\s+basura",
    r"eres\s+basura",
    r"mierda",
    r"puta",
    r"puto",
    r"maldito",
    r"maldita",
    r"h[íi]gado?\b",
    r"cabr[oó]n",
    r"cabrona",
    r"hijo\s+de\s+puta",
    r"hijo\s+de\s+la\s+gran\s+puta",
    r"callate",
    r"cállate",
    r"cerdo",
    r"imbecilazo",
    r"idiot[oa]s?",
    r"est[úu]pido\s+del\s+c.*",
    r"no\s+vales\s+un\s+centavo",
    r"sin\s+valor",
    r"inútil",
    r"inutil\b",
    r"eres\s+inservible",
    r"no\s+sirves\s+para\s+nada",
    r"me\s+das\s+asco",
    r"eres\s+un\s+idiota",
    r"eres\s+una\s+idiota",
    r"malnacido",
    r"malnacida",
    r"te\s+odio",
    r"odia\s+esto",
    r"put[ao]s?",
    r"carajo",
    r"chingad[oó]",
    r"vete\s+ya",
    r"vete\s+de\s+aqui",
    r"que\s+te\s+vaya\s+mal",
    r"no\s+me\s+interesas",
]


def sanitize_input(message: str) -> Tuple[str, bool, bool]:
    """
    Limpia entrada y detecta inyecciones o abuso directo.
    Retorna: (mensaje limpio, es_inyeccion, es_desagradable)
    """
    # Validar longitud
    if len(message) > settings.max_message_length:
        return "", True, False

    # Eliminar saltos y caracteres de control inusuales
    cleaned = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f]", " ", message)
    cleaned = cleaned.strip()

    if not cleaned:
        return "", True, False

    # Detectar patrones de inyección
    for pattern in INJECTION_PATTERNS:
        if re.search(pattern, cleaned, re.IGNORECASE):
            return cleaned, True, False

    # Detectar trato agresivo directo
    for pattern in RUDENESS_PATTERNS:
        if re.search(pattern, cleaned, re.IGNORECASE):
            return cleaned, False, True

    return cleaned, False, False


def filter_output(response: str) -> str:
    """Valida que salida no esté vacía."""
    if not response or not response.strip():
        return "No cuento con información suficiente sobre eso. Te invito a contactarnos directamente en nuestro portal."
    return response.strip()
